# Generated by Django 5.0.6 on 2024-06-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('precipitation', models.IntegerField()),
                ('station_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'unique_together': {('date', 'station_id')},
            },
        ),
        migrations.CreateModel(
            name='WeatherStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('avg_max_temp', models.FloatField(null=True)),
                ('avg_min_temp', models.FloatField(null=True)),
                ('total_precipitation', models.FloatField(null=True)),
                ('station_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'unique_together': {('year', 'station_id')},
            },
        ),
    ]
